add_subdirectory(logger)
add_subdirectory(log)
add_subdirectory(json_io)
add_subdirectory(string_utils)
add_subdirectory(note_history)
add_subdirectory(tiny_json)
add_subdirectory(imgui_md)
add_subdirectory(markdown_code_highlight)
add_subdirectory(markdown_sections)
add_subdirectory(markdown_tables)
add_subdirectory(markdown_view)
add_subdirectory(mermaid)
add_subdirectory(markdown_images)
add_subdirectory(markdown_ui)
add_subdirectory(markdown_support)
add_subdirectory(markdown_editor)
add_subdirectory(note_ui)
add_subdirectory(note_project)
add_subdirectory(emoji_picker)
add_subdirectory(lang)
add_subdirectory(note_model)
add_subdirectory(note_storage)
