add_library(markdown_support STATIC src/markdown_support.cpp)
target_include_directories(markdown_support PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/inc)
target_link_libraries(markdown_support PUBLIC string_utils mermaid imgui nlohmann_json::nlohmann_json markdown_ui markdown_sections markdown_view markdown_editor markdown_tables)
