cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ASSET_ROOT OR NOT DEFINED OUTPUT_HPP OR NOT DEFINED OUTPUT_CPP)
  message(FATAL_ERROR "ASSET_ROOT, OUTPUT_HPP, and OUTPUT_CPP must be defined")
endif()

file(GLOB_RECURSE ASSET_FILES LIST_DIRECTORIES false RELATIVE "${ASSET_ROOT}" "${ASSET_ROOT}/*")

function(append_line path line)
  file(APPEND "${path}" "${line}\n")
endfunction()

function(write_asset_byte_array path variable_name asset_hex)
  string(LENGTH "${asset_hex}" asset_hex_len)
  if(asset_hex_len EQUAL 0)
    append_line("${path}" "static const unsigned char ${variable_name}[] = {};")
    return()
  endif()

  append_line("${path}" "static const unsigned char ${variable_name}[] = {")

  math(EXPR asset_byte_count "${asset_hex_len} / 2")
  math(EXPR max_index "${asset_byte_count} - 1")
  foreach(byte_index RANGE 0 ${max_index} 16)
    math(EXPR offset "${byte_index} * 2")
    math(EXPR remaining "${asset_byte_count} - ${byte_index}")
    if(remaining GREATER 16)
      set(line_bytes 16)
    else()
      set(line_bytes "${remaining}")
    endif()

    math(EXPR chunk_len "${line_bytes} * 2")
    string(SUBSTRING "${asset_hex}" "${offset}" "${chunk_len}" chunk_hex)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " chunk_bytes "${chunk_hex}")
    string(REGEX REPLACE ", $" "" chunk_bytes "${chunk_bytes}")
    append_line("${path}" "  ${chunk_bytes},")
  endforeach()

  append_line("${path}" "};")
endfunction()

file(WRITE "${OUTPUT_HPP}" "#pragma once\n\n#include <cstddef>\n#include <string_view>\n\nnamespace NoteppEmbeddedAssets\n{\nstruct AssetSpan\n{\n  const unsigned char *data = nullptr;\n  size_t size = 0;\n\n  constexpr explicit operator bool() const noexcept\n  {\n    return data != nullptr;\n  }\n};\n\nAssetSpan find_asset(std::string_view path);\nbool has_asset(std::string_view path);\n} // namespace NoteppEmbeddedAssets\n")

file(WRITE "${OUTPUT_CPP}" "#include \"embedded_assets.hpp\"\n\n#include <string>\n#include <string_view>\n\nnamespace NoteppEmbeddedAssets\n{\nnamespace\n{\nstruct AssetEntry\n{\n  std::string_view path;\n  const unsigned char *data;\n  size_t size;\n};\n\nstd::string normalize_path(std::string_view path)\n{\n  std::string normalized(path);\n  for(char &ch : normalized)\n  {\n    if(ch == '\\\\') ch = '/';\n  }\n\n  while(normalized.rfind(\"./\", 0) == 0)\n  {\n    normalized.erase(0, 2);\n  }\n\n  while(normalized.rfind(\"/\", 0) == 0)\n  {\n    normalized.erase(0, 1);\n  }\n\n  if(normalized.rfind(\"assets/\", 0) == 0)\n  {\n    normalized.erase(0, 7);\n  }\n\n  return normalized;\n}\n\n")

set(asset_entries "")
foreach(asset_file IN LISTS ASSET_FILES)
  string(REPLACE "\\" "/" asset_norm "${asset_file}")
  string(REGEX REPLACE "[^A-Za-z0-9_]" "_" asset_id "${asset_norm}")
  set(asset_abs "${ASSET_ROOT}/${asset_file}")
  file(READ "${asset_abs}" asset_hex HEX)
  file(SIZE "${asset_abs}" asset_size)
  write_asset_byte_array("${OUTPUT_CPP}" "asset_${asset_id}" "${asset_hex}")
  string(APPEND asset_entries "  {\"${asset_norm}\", reinterpret_cast<const unsigned char *>(asset_${asset_id}), ${asset_size}},\n")
endforeach()

append_line("${OUTPUT_CPP}" "static const AssetEntry kAssets[] = {")
file(APPEND "${OUTPUT_CPP}" "${asset_entries}")
append_line("${OUTPUT_CPP}" "};")
append_line("${OUTPUT_CPP}" "} // namespace")
append_line("${OUTPUT_CPP}" "")
append_line("${OUTPUT_CPP}" "AssetSpan find_asset(std::string_view path)")
append_line("${OUTPUT_CPP}" "{")
append_line("${OUTPUT_CPP}" "  const std::string normalized = normalize_path(path);")
append_line("${OUTPUT_CPP}" "  for(const AssetEntry &entry : kAssets)")
append_line("${OUTPUT_CPP}" "  {")
append_line("${OUTPUT_CPP}" "    if(entry.path == normalized) return AssetSpan{entry.data, entry.size};")
append_line("${OUTPUT_CPP}" "  }")
append_line("${OUTPUT_CPP}" "  return {};")
append_line("${OUTPUT_CPP}" "}")
append_line("${OUTPUT_CPP}" "")
append_line("${OUTPUT_CPP}" "bool has_asset(std::string_view path)")
append_line("${OUTPUT_CPP}" "{")
append_line("${OUTPUT_CPP}" "  return static_cast<bool>(find_asset(path));")
append_line("${OUTPUT_CPP}" "}")
append_line("${OUTPUT_CPP}" "} // namespace NoteppEmbeddedAssets")
